BBG_EXCH_LOOKUP = {'AQSE': 'PZ',
  'Abidjan': 'IA',
  'Albania': 'AL',
  'Algeria': 'AG',
  'Andorra': 'AD',
  'Angola': 'AX',
  'Anguilla': 'AI',
  'Aquis Exchange': 'QE',
  'Aquis Exchg': 'QX',
  'Argentina': 'AR',
  'AsstMtch MTF': 'A0',
  'Australia': 'AU',
  'Austria': 'AV',
  'Azerbaijan': 'AZ',
  'BATS Europe': 'EB',
  'BMTF - ETF': 'B2',
  'BRVM Regional': 'BC',
  'Bahamas': 'BM',
  'Bangladesh': 'BD',
  'Barbados': 'BA',
  'Belarus': 'RB',
  'Belgium': 'BB',
  'Belize': 'ZB',
  'Bermuda': 'BH',
  'Blockmatch': 'B3',
  'Bolivia': 'VB',
  'Botswana': 'BG',
  'Brazil': 'BZ',
  'Brit Virgin Is': 'VI',
  'Brunei': 'BX',
  'Bulgaria': 'BU',
  'Burgundy': 'BY',
  'Cambodia': 'KH',
  'Cameroon': 'DE',
  'Canada': 'CN',
  'Cape Verde': 'VR',
  'Cayman Islands': 'KY',
  'Cboe APA EU': 'X2',
  'Cboe BXE EU': 'E2',
  'Cboe CXE EU': 'I2',
  'Central Afr Rp': 'ZC',
  'Chi-East': 'HE',
  'Chi-X Europe': 'IX',
  'Chile': 'CI',
  'China': 'CH',
  'Colombia': 'CB',
  'Cook Islands': 'CU',
  'Costa Rica': 'CR',
  'Croatia': 'CZ',
  'Cyprus': 'CY',
  'Czech Republic': 'CP',
  'Damascus SecEx': 'SY',
  'Denmark': 'DC',
  'Eastern Carrib': 'EK',
  'Ecuador': 'ED',
  'Egypt(EGX)': 'EY',
  'El Salvador': 'EL',
  'Equiduct': 'BQ',
  'Estonia': 'ET',
  'Eswatini': 'SD',
  'Euro Comp': 'EU',
  'EuroTLX': 'TE',
  'Fed of Bos/Her': 'BT',
  'Fiji': 'FS',
  'Finland': 'FH',
  'France': 'FP',
  'GXG Markets': 'G4',
  'Gabon': 'ZG',
  'Gambia': 'GX',
  'Georgia': 'GG',
  'German NM': 'NM',
  'Germany': 'GR',
  'Gettex': 'GZ',
  'Ghana': 'GN',
  'Gibraltar': 'TL',
  'Greece': 'GA',
  'Guatemala': 'GL',
  'Guernsey': 'GU',
  'HI-MTF': 'HM',
  'Honduras': 'HO',
  'Hong Kong': 'HK',
  'Hungary': 'HB',
  'ITG Posit': 'PO',
  'Iceland': 'IR',
  'India': 'IN',
  'Indonesia': 'IJ',
  'Iran': 'IE',
  'Iraq Stock Ex': 'IQ',
  'Ireland': 'ID',
  'Isle of Man': 'IO',
  'Israel': 'IT',
  'Italy': 'IM',
  'Jamaica': 'JA',
  'Japan': 'JP',
  'Jersey': 'JY',
  'Jordan': 'JR',
  'KSE': 'KS',
  'Kabul Intl': 'AK',
  'Kazakhstan': 'KZ',
  'Kenya': 'KN',
  'Khartoum Stock Exchange': 'S3',
  'KoreaFrBMkt': 'KF',
  'Kosovo': 'KO',
  'Kuwait': 'KK',
  'Kyrgyzstan': 'KB',
  'Lang & Schwarz Exchange - LSX': 'LA',
  'Lang & Schwarz Exchange - Systematic Internalizer': 'LU',
  'Laos SE': 'LS',
  'Latinex': 'PP',
  'Latvia': 'LR',
  'Lebanon': 'LB',
  'Libn Arb Jmhra': 'LY',
  'Liechtenstein': 'LE',
  'Liquidnet': 'L3',
  'Liquidnet IR - CB3C': 'L1',
  'Lithuania': 'LH',
  'London Intl': 'LI',
  'Luxembourg': 'LX',
  'MESDAQ': 'MQ',
  'MICEX': 'RM',
  'MS MTF': 'M0',
  'Macau': 'MA',
  'Macedonia': 'MS',
  'Malawi SE': 'MW',
  'Malaysia': 'MK',
  'Maldives': 'MX',
  'Manama': 'BI',
  'Marshall Islds': 'MI',
  'Mexico': 'MM',
  'Moldova': 'MB',
  'Monaco': 'MN',
  'Mongolia': 'MO',
  'Montenegro': 'ME',
  'Morocco': 'MC',
  'Mozambique': 'MZ',
  'NASDAQ Europe': 'ES',
  'NASDAQ OMX Arm': 'AY',
  'NDQ Deutschlnd': 'ND',
  'NYSE ARCA Eu': 'NR',
  'NYSE EU London': 'LD',
  'Namibia': 'NW',
  'Nasdaq Dubai': 'DU',
  'Nepal': 'NK',
  'Neth Antilles': 'NT',
  'Netherlands': 'NA',
  'Nevis': 'NX',
  'New Zealand': 'NZ',
  'Nicaragua': 'NC',
  'Nigeria': 'NL',
  'Norway': 'NO',
  'Nth SSE-SEHK': 'C1',
  'Nth SZ-SEHK': 'C2',
  'OFEX London': 'OF',
  'OTC Composite': 'EO',
  'Oman': 'OM',
  'PLUS Europe': 'PG',
  'PNGX Market Limited': 'PB',
  'Pakistan': 'PA',
  'Palestine': 'PS',
  'Paraguay': 'PN',
  'Peru': 'PE',
  'Philippines': 'PM',
  'Poland': 'PW',
  'Portugal': 'PL',
  'Qatar': 'QD',
  'Quotrix Exchg': 'QT',
  'Romania': 'RO',
  'Rpblika Srpska': 'BK',
  'Russia': 'RU',
  'Rwanda': 'RW',
  'SEM': 'MP',
  'SIGMA-X EU MTF': 'S4',
  'SIX Swiss Exch': 'VX',
  'Saudi Arabia': 'AB',
  'Senegal': 'ZS',
  'Serbia': 'SG',
  'Seychelles': 'SZ',
  'SharesPost': 'SH',
  'Sierra Leone': 'SU',
  'Sigma X MTF': 'S1',
  'Singapore': 'SP',
  'Slovakia': 'SK',
  'Slovenia': 'SV',
  'South Africa': 'SJ',
  'Spain': 'SM',
  'Sri Lanka': 'SL',
  'Sth SSE-SEHK': 'H1',
  'Sth SZ-SEHK': 'H2',
  'Sweden': 'SS',
  'Switzerland': 'SW',
  'TOM MTF': 'MT',
  'Taiwan': 'TT',
  'Tajikistan': 'TD',
  'Tanzania': 'TZ',
  'Thailand': 'TB',
  'TradeWeb MTF': 'T2',
  'Tradegate': 'TH',
  'Trinidad': 'TP',
  'Tunisia': 'TU',
  'Turkey': 'TI',
  'Turkmenistan': 'TM',
  'Turks & Caico': 'TC',
  'Turquoise Eu': 'T1',
  'Turquoise Mkt': 'TQ',
  'UAE': 'UH',
  'UBS MTF': 'S2',
  'Uganda': 'UG',
  'Ukraine': 'UZ',
  'United Kingdom': 'LN',
  'United States': 'US',
  'Uruguay': 'UY',
  'Uzbekistan': 'ZU',
  'Valetta': 'MV',
  'Venezuela': 'VC',
  'Vietnam': 'VN',
  'Xetra Intl Mkt': 'GK',
  'Yemen': 'YS',
  'Zambia': 'ZL',
  'Zimbabwe': 'ZH'}